Repository ucsb-cs156-f24/proj-courses-f24-03, pull requests merged in 2024-11, with the labels that each got.

#12 Suppress Warning
  pom.xml
Labels: FIXME-Team CR, FIXME-PR Description

#14 Implemented getActiveQuarterList method
  src/main/java/edu/ucsb/cs156/courses/controllers/UCSBAPIQuarterController.java
  src/main/java/edu/ucsb/cs156/courses/services/UCSBAPIQuarterService.java
  src/test/java/edu/ucsb/cs156/courses/controllers/UCSBAPIQuarterControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/services/UCSBAPIQuarterServiceTests.java
Labels: 10

#15 Reduce clutter in log from course update jobs
  src/main/java/edu/ucsb/cs156/courses/jobs/UpdateCourseDataJob.java
  src/test/java/edu/ucsb/cs156/courses/jobs/UpdateCourseDataJobTests.java
Labels: 5, Merge Candidate-CI

#22 Feature: Admins can now purge job log
  frontend/src/main/components/Jobs/ClearJobLogsForm.js
  frontend/src/main/pages/Admin/AdminJobsPage.js
  frontend/src/tests/components/Jobs/TestClearJobLogForm.test.js
  frontend/src/tests/pages/AdminJobsPage.test.js
Labels: 10, Merge Candidate-CI

#24 Create AdminUpdatesPage Placeholder
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/Admin/AdminUpdatesPage.js
  frontend/src/stories/pages/Admin/AdminUpdatesPage.stories.js
  frontend/src/tests/pages/AdminUpdatesPage.test.js
Labels: 5, Merge Candidate-CI, f24-5pm-3

#34 Makes Description Optional on Personal Schedule, attempt 2
  frontend/src/main/components/PersonalSchedules/PersonalScheduleForm.js
  frontend/src/tests/components/PersonalSchedules/PersonalScheduleForm.test.js
Labels: 5, Merge Candidate-CI

#40 Entity and Repository classes for finals endpoint
  src/main/java/edu/ucsb/cs156/courses/entities/FinalsEntity.java
  src/main/java/edu/ucsb/cs156/courses/repositories/FinalsRepository.java
Labels: 5, Merge Candidate-CI

#29 Detailed log page for long running jobs
  frontend/src/App.js
  frontend/src/main/components/Jobs/JobsLogTable.js
  frontend/src/main/pages/Jobs/JobsLogPage.js
  frontend/src/tests/components/Jobs/JobsLogsTable.test.js
  frontend/src/tests/pages/Jobs/JobsLogPage.test.js
Labels: 10

#31 Add Link to Detailed Log Page
  frontend/src/main/components/Jobs/JobsTable.js
  frontend/src/tests/components/Jobs/JobsTable.test.js
  frontend/src/tests/pages/AdminJobsPage.test.js
Labels: 10, Merge Candidate-CI

#42 replaced duplicate sections error message
  frontend/src/main/components/Sections/SectionsTable.js
  frontend/src/tests/components/Sections/SectionsTable.test.js
  src/main/java/edu/ucsb/cs156/courses/controllers/PSCourseController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PSCourseControllerTests.java
Labels: 10, Merge Candidate-CI
